<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    /**
     * Lista de paises
     * @var array
     */
    public static $countries = [
        "AF" => "Afganistán",
        "AL" => "Albania",
        "DE" => "Alemania",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguila",
        "AG" => "Antigua y Barbuda",
        "AN" => "Antillas Neerlandesas",
        "AQ" => "Antártida",
        "SA" => "Arabia Saudí",
        "DZ" => "Argelia",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaiyán",
        "BS" => "Bahamas",
        "BH" => "Bahréin",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BZ" => "Belice",
        "BJ" => "Benín",
        "BM" => "Bermudas",
        "BY" => "Bielorrusia",
        "BO" => "Bolivia",
        "BA" => "Bosnia-Herzegovina",
        "BW" => "Botsuana",
        "BR" => "Brasil",
        "BN" => "Brunéi",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "BT" => "Bután",
        "BE" => "Bélgica",
        "CV" => "Cabo Verde",
        "KH" => "Camboya",
        "CM" => "Camerún",
        "CA" => "Canadá",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CY" => "Chipre",
        "VA" => "Ciudad del Vaticano",
        "CO" => "Colombia",
        "KM" => "Comoras",
        "CG" => "Congo",
        "KP" => "Corea del Norte",
        "KR" => "Corea del Sur",
        "CR" => "Costa Rica",
        "CI" => "Costa de Marfil",
        "HR" => "Croacia",
        "CU" => "Cuba",
        "DK" => "Dinamarca",
        "DM" => "Dominica",
        "EC" => "Ecuador",
        "EG" => "Egipto",
        "SV" => "El Salvador",
        "AE" => "Emiratos Árabes Unidos",
        "ER" => "Eritrea",
        "SK" => "Eslovaquia",
        "SI" => "Eslovenia",
        "ES" => "España",
        "US" => "Estados Unidos",
        "EE" => "Estonia",
        "ET" => "Etiopía",
        "PH" => "Filipinas",
        "FI" => "Finlandia",
        "FJ" => "Fiyi",
        "FR" => "Francia",
        "GA" => "Gabón",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GD" => "Granada",
        "GR" => "Grecia",
        "GL" => "Groenlandia",
        "GP" => "Guadalupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GF" => "Guayana Francesa",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GQ" => "Guinea Ecuatorial",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haití",
        "HN" => "Honduras",
        "HU" => "Hungría",
        "IN" => "India",
        "ID" => "Indonesia",
        "IQ" => "Iraq",
        "IE" => "Irlanda",
        "IR" => "Irán",
        "BV" => "Isla Bouvet",
        "CX" => "Isla Christmas",
        "NU" => "Isla Niue",
        "NF" => "Isla Norfolk",
        "IM" => "Isla de Man",
        "IS" => "Islandia",
        "KY" => "Islas Caimán",
        "CC" => "Islas Cocos",
        "CK" => "Islas Cook",
        "FO" => "Islas Feroe",
        "GS" => "Islas Georgia del Sur y Sandwich del Sur",
        "HM" => "Islas Heard y McDonald",
        "FK" => "Islas Malvinas",
        "MP" => "Islas Marianas del Norte",
        "MH" => "Islas Marshall",
        "SB" => "Islas Salomón",
        "TC" => "Islas Turcas y Caicos",
        "VG" => "Islas Vírgenes Británicas",
        "VI" => "Islas Vírgenes de los Estados Unidos",
        "UM" => "Islas menores alejadas de los Estados Unidos",
        "AX" => "Islas Åland",
        "IL" => "Israel",
        "IT" => "Italia",
        "JM" => "Jamaica",
        "JP" => "Japón",
        "JE" => "Jersey",
        "JO" => "Jordania",
        "KZ" => "Kazajistán",
        "KE" => "Kenia",
        "KG" => "Kirguistán",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "LA" => "Laos",
        "LS" => "Lesoto",
        "LV" => "Letonia",
        "LR" => "Liberia",
        "LY" => "Libia",
        "LI" => "Liechtenstein",
        "LT" => "Lituania",
        "LU" => "Luxemburgo",
        "LB" => "Líbano",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MY" => "Malasia",
        "MW" => "Malaui",
        "MV" => "Maldivas",
        "ML" => "Mali",
        "MT" => "Malta",
        "MA" => "Marruecos",
        "MQ" => "Martinica",
        "MU" => "Mauricio",
        "MR" => "Mauritania",
        "YT" => "Mayotte",
        "FM" => "Micronesia",
        "MD" => "Moldavia",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "MX" => "México",
        "MC" => "Mónaco",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NI" => "Nicaragua",
        "NG" => "Nigeria",
        "NO" => "Noruega",
        "NC" => "Nueva Caledonia",
        "NZ" => "Nueva Zelanda",
        "NE" => "Níger",
        "OM" => "Omán",
        "PK" => "Pakistán",
        "PW" => "Palau",
        "PS" => "Palestina",
        "PA" => "Panamá",
        "PG" => "Papúa Nueva Guinea",
        "PY" => "Paraguay",
        "NL" => "Países Bajos",
        "PE" => "Perú",
        "PN" => "Pitcairn",
        "PF" => "Polinesia Francesa",
        "PL" => "Polonia",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "HK" => "Región Administrativa Especial de Hong Kong de la República Popular China",
        "MO" => "Región Administrativa Especial de Macao de la República Popular China",
        "ZZ" => "Región desconocida o no válida",
        "GB" => "Reino Unido",
        "CF" => "República Centroafricana",
        "CZ" => "República Checa",
        "CD" => "República Democrática del Congo",
        "DO" => "República Dominicana",
        "RE" => "Reunión",
        "RW" => "Ruanda",
        "RO" => "Rumanía",
        "RU" => "Rusia",
        "WS" => "Samoa",
        "AS" => "Samoa Americana",
        "BL" => "San Bartolomé",
        "KN" => "San Cristóbal y Nieves",
        "SM" => "San Marino",
        "MF" => "San Martín",
        "PM" => "San Pedro y Miquelón",
        "VC" => "San Vicente y las Granadinas",
        "SH" => "Santa Elena",
        "LC" => "Santa Lucía",
        "ST" => "Santo Tomé y Príncipe",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "CS" => "Serbia y Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leona",
        "SG" => "Singapur",
        "SY" => "Siria",
        "SO" => "Somalia",
        "LK" => "Sri Lanka",
        "SZ" => "Suazilandia",
        "ZA" => "Sudáfrica",
        "SD" => "Sudán",
        "SE" => "Suecia",
        "CH" => "Suiza",
        "SR" => "Surinam",
        "SJ" => "Svalbard y Jan Mayen",
        "EH" => "Sáhara Occidental",
        "TH" => "Tailandia",
        "TW" => "Taiwán",
        "TZ" => "Tanzania",
        "TJ" => "Tayikistán",
        "IO" => "Territorio Británico del Océano Índico",
        "TF" => "Territorios Australes Franceses",
        "TL" => "Timor Oriental",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad y Tobago",
        "TM" => "Turkmenistán",
        "TR" => "Turquía",
        "TV" => "Tuvalu",
        "TN" => "Túnez",
        "UA" => "Ucrania",
        "UG" => "Uganda",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistán",
        "VU" => "Vanuatu",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WF" => "Wallis y Futuna",
        "YE" => "Yemen",
        "DJ" => "Yibuti",
        "ZM" => "Zambia",
        "ZW" => "Zimbabue",
    ];
    /**
     * Lista de provincias
     * @var array
     */
    public static $provinces = [
        '2' => 'Álava',
        '3' => 'Albacete',
        '4' => 'Alicante/Alacant',
        '5' => 'Almería',
        '6' => 'Asturias',
        '7' => 'Ávila',
        '8' => 'Badajoz',
        '9' => 'Barcelona',
        '10' => 'Burgos',
        '11' => 'C&aacute;ceres',
        '12' => 'C&aacute;diz',
        '13' => 'Cantabria',
        '14' => 'Castellón/Castelló',
        '15' => 'Ceuta',
        '16' => 'Ciudad Real',
        '17' => 'Córdoba',
        '18' => 'Cuenca',
        '19' => 'Girona',
        '20' => 'Las Palmas',
        '21' => 'Granada',
        '22' => 'Guadalajara',
        '23' => 'Guipúzcoa',
        '24' => 'Huelva',
        '25' => 'Huesca',
        '26' => 'Illes Balears',
        '27' => 'Jaén',
        '28' => 'A Coru&ntilde;a',
        '29' => 'La Rioja',
        '30' => 'León',
        '31' => 'Lleida',
        '32' => 'Lugo',
        '33' => 'Madrid',
        '34' => 'Málaga',
        '35' => 'Melilla',
        '36' => 'Murcia',
        '37' => 'Navarra',
        '38' => 'Ourense',
        '39' => 'Palencia',
        '40' => 'Pontevedra',
        '41' => 'Salamanca',
        '42' => 'Segovia',
        '43' => 'Sevilla',
        '44' => 'Soria',
        '45' => 'Tarragona',
        '46' => 'Santa Cruz de Tenerife',
        '47' => 'Teruel',
        '48' => 'Toledo',
        '49' => 'Valencia/Valéncia',
        '50' => 'Valladolid',
        '51' => 'Vizcaya',
        '52' => 'Zamora',
        '53' => 'Zaragoza'
    ];

    public function facturas()
    {
        return $this->hasMany('App\Factura');
    }

    public function proyectos()
    {
        return $this->hasMany('App\Proyecto');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function last_update_user()
    {
        return $this->belongsTo('App\User','last_update_user_id');
    }
}
