<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    public static $languages = [
        'ab' => 'Abjasio',
        'aa' => 'Afar',
        'af' => 'Afrikáans',
        'ak' => 'Akano',
        'ay' => 'Aimara',
        'sq' => 'Albano',
        'de' => 'Alemán',
        'am' => 'Amhárico',
        'ar' => 'Árabe',
        'an' => 'Aragonés',
        'hy' => 'Armenio',
        'as' => 'Asamés',
        'av' => 'Ávaro',
        'ae' => 'Avéstico',
        'az' => 'Azerí',
        'bm' => 'Bambara',
        'ba' => 'Baskir',
        'bn' => 'Bengalí',
        'bh' => 'Bhoyapurí',
        'be' => 'Bieloruso',
        'my' => 'Birmano',
        'bi' => 'Bislama',
        'bs' => 'Bosnio',
        'br' => 'Bretón',
        'bg' => 'Búlgaro',
        'ks' => 'Cachemiro',
        'km' => 'Camboyano',
        'kn' => 'Canarés',
        'ca' => 'Catalán',
        'ch' => 'Chamorro',
        'ce' => 'Checheno',
        'cs' => 'Checo',
        'ny' => 'Chichewa',
        'zh' => 'Chino',
        'za' => 'Chuan',
        'cv' => 'Chuvasio',
        'si' => 'Cingalés',
        'ko' => 'Coreano',
        'kw' => 'Córnico',
        'co' => 'Corso',
        'cr' => 'Cree',
        'hr' => 'Croata',
        'da' => 'Danés',
        'dz' => 'Dzongkha',
        'cu' => 'Eslavo eclesiástico antiguo',
        'sk' => 'Eslovaco',
        'sl' => 'Esloveno',
        'es' => 'Español',
        'eo' => 'Esperanto',
        'et' => 'Estonio',
        'eu' => 'Euskera',
        'ee' => 'Ewé',
        'fo' => 'Feroés',
        'fi' => 'Finés',
        'fj' => 'Fiyiano',
        'fr' => 'Francés',
        'fy' => 'Frisón',
        'ff' => 'Fula',
        'gd' => 'Gaélico escocés ',
        'cy' => 'Galés',
        'gl' => 'Gallego',
        'ka' => 'Georgiano',
        'el' => 'Griego (moderno)',
        'kl' => 'Groenlandés',
        'gn' => 'Guaraní',
        'gu' => 'Guyaratí',
        'ht' => 'Haitiano',
        'ha' => 'Hausa',
        'he' => 'Hebreo',
        'hz' => 'Herero',
        'hi' => 'Hindi',
        'ho' => 'Hiri Motu',
        'nl' => 'Holandés',
        'hu' => 'Húngaro',
        'io' => 'Ido',
        'ig' => 'Igbo',
        'id' => 'Indonesio',
        'en' => 'Inglés',
        'ia' => 'Interlingua',
        'iu' => 'Inuktitut',
        'ik' => 'Iñupiaq',
        'ga' => 'Irlandés',
        'is' => 'Islandés',
        'it' => 'Italiano',
        'ja' => 'Japonés',
        'jv' => 'Javanés',
        'kr' => 'Kanuri',
        'kk' => 'Kazajo',
        'ki' => 'Kikuyu',
        'ky' => 'Kirguís',
        'rn' => 'Kirundi',
        'kv' => 'Komi',
        'kg' => 'Kongo',
        'kj' => 'Kuanyama',
        'ku' => 'Kurdo',
        'lo' => 'Lao',
        'la' => 'Latín',
        'lv' => 'Latón',
        'li' => 'Limburgués',
        'ln' => 'Lingala',
        'lt' => 'Lituano',
        'lu' => 'Luba-Katanga',
        'lg' => 'Luganda',
        'lb' => 'Luxemburgués',
        'dv' => 'Maldivo',
        'mk' => 'Macedonio',
        'ml' => 'Malayalam',
        'ms' => 'Malayo',
        'mg' => 'Malgache',
        'mt' => 'Maltés',
        'gv' => 'Manés',
        'mi' => 'Maorí',
        'mr' => 'Maratí',
        'mh' => 'Marshalés',
        'mn' => 'Mongol',
        'na' => 'Nauruano',
        'nv' => 'Navajo',
        'nd' => 'Ndebele del norte',
        'nr' => 'Ndebele del sur',
        'ng' => 'Ndonga',
        'ne' => 'Nepalí',
        'no' => 'Noruego',
        'nb' => 'Noruego Bokmål',
        'nn' => 'Noruego Nynorsk',
        'ie' => 'Occidental',
        'oc' => 'Occitano',
        'oj' => 'Ojibwa',
        'or' => 'Oriya',
        'om' => 'Oromo',
        'os' => 'Osético ',
        'pi' => 'Pali',
        'pa' => 'Panyabí ',
        'ps' => 'Pastú',
        'fa' => 'Persa',
        'pl' => 'Polaco',
        'pt' => 'Portugués',
        'qu' => 'Quechua',
        'rm' => 'Romanche',
        'rw' => 'Ruandés',
        'ro' => 'Rumano',
        'ru' => 'Ruso',
        'se' => 'Sami septentrional',
        'sm' => 'Samoano',
        'sg' => 'Sango',
        'sa' => 'Sánscrito',
        'sc' => 'Sardo',
        'sr' => 'Serbio',
        'st' => 'Sesotho',
        'tn' => 'Setsuana',
        'sn' => 'Shona',
        'sd' => 'Sindhi',
        'so' => 'Somalí',
        'sw' => 'Suajili',
        'ss' => 'Suazi',
        'sv' => 'Sueco',
        'su' => 'Sundanés',
        'tl' => 'Tagalo',
        'ty' => 'Tahitiano',
        'th' => 'Tailandés',
        'ta' => 'Tamil',
        'tt' => 'Tártaro',
        'tg' => 'Tayiko',
        'te' => 'Télugu',
        'bo' => 'Tibetano',
        'ti' => 'Tigriña',
        'to' => 'Tongano',
        'ts' => 'Tsonga',
        'tr' => 'Turco',
        'tk' => 'Turcomano',
        'tw' => 'Twi',
        'uk' => 'Ucraniano',
        'ug' => 'Uigur',
        'ur' => 'Urdu',
        'uz' => 'Uzbeko',
        'wa' => 'Valón',
        've' => 'Venda',
        'vi' => 'Vietnamíta',
        'vo' => 'Volapük',
        'wo' => 'Wolof',
        'xh' => 'Xhosa',
        'ii' => 'Yi de Sichuán',
        'yi' => 'Yídish',
        'yo' => 'Yoruba',
        'zu' => 'Zulú'
    ];

    public function audio()
    {
        return $this->hasMany('App\Audio');
    }

    public function videos()
    {
        return $this->hasMany('App\Video');
    }

    public function texts()
    {
        return $this->hasMany('App\Text');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function last_update_user()
    {
        return $this->belongsTo('App\User','last_update_user_id');
    }
}
