<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    public static $languages = [
    'ab' => 'Abjasio',
    'aa' => 'Afar',
    'af' => 'Afrikáans',
    'ak' => 'Akano',
    'sq' => 'Albano',
    'am' => 'Amhárico',
    'ar' => 'Árabe',
    'an' => 'Aragonés',
    'hy' => 'Armenio',
    'as' => 'Asamés',
    'av' => 'Ávaro',
    'ae' => 'Avéstico',
    'ay' => 'Aimara',
    'az' => 'Azerí',
    'bm' => 'Bambara',
    'ba' => 'Baskir',
    'eu' => 'Euskera',
    'be' => 'Bieloruso',
    'bn' => 'Bengalí',
    'bh' => 'Bhoyapurí',
    'bi' => 'Bislama',
    'bs' => 'Bosnio',
    'br' => 'Bretón',
    'bg' => 'Búlgaro',
    'my' => 'Birmano',
    'ca' => 'Catalán',
    'km' => 'Camboyano',
    'ch' => 'Chamorro',
    'ce' => 'Checheno',
    'ny' => 'Chichewa',
    'zh' => 'Chino',
    'cu' => 'Eslavo eclesiástico antiguo',
    'cv' => 'Chuvasio',
    'kw' => 'Córnico',
    'co' => 'Corso',
    'cr' => 'Cree',
    'hr' => 'Croata',
    'cs' => 'Checo',
    'da' => 'Danés',
    'dv' => 'Maldivo',
    'nl' => 'Holandés',
    'dz' => 'Dzongkha',
    'en' => 'Inglés',
    'eo' => 'Esperanto',
    'et' => 'Estonio',
    'ee' => 'Ewé',
    'fo' => 'Feroés',
    'fj' => 'Fiyiano',
    'fi' => 'Finés',
    'fr' => 'Francés',
    'ff' => 'Fula',
    'gd' => 'Gaélico escocés ',
    'gl' => 'Gallego',
    'lg' => 'Luganda',
    'ka' => 'Georgiano',
    'de' => 'Alemán',
    'ki' => 'Kikuyu',
    'el' => 'Griego (moderno)',
    'kl' => 'Groenlandés',
    'gn' => 'Guaraní',
    'gu' => 'Guyaratí',
    'ht' => 'Haitiano',
    'ha' => 'Hausa',
    'he' => 'Hebreo',
    'hz' => 'Herero',
    'hi' => 'Hindi',
    'ho' => 'Hiri Motu',
    'hu' => 'Húngaro',
    'is' => 'Islandés',
    'io' => 'Ido',
    'ig' => 'Igbo',
    'id' => 'Indonesio',
    'ia' => 'Interlingua',
    'ie' => 'Occidental',
    'iu' => 'Inuktitut',
    'ik' => 'Iñupiaq',
    'ga' => 'Irlandés',
    'it' => 'Italiano',
    'ja' => 'Japonés',
    'jv' => 'Javanés',
    'kn' => 'Canarés',
    'kr' => 'Kanuri',
    'ks' => 'Cachemiro',
    'kk' => 'Kazajo',
    'rw' => 'Ruandés',
    'kv' => 'Komi',
    'kg' => 'Kongo',
    'ko' => 'Coreano',
    'kj' => 'Kuanyama',
    'ku' => 'Kurdo',
    'ky' => 'Kirguís',
    'lo' => 'Lao',
    'la' => 'Latín',
    'lv' => 'Latón',
    'lb' => 'Luxemburgués',
    'li' => 'Limburgués',
    'ln' => 'Lingala',
    'lt' => 'Lituano',
    'lu' => 'Luba-Katanga',
    'mk' => 'Macedonio',
    'mg' => 'Malgache',
    'ms' => 'Malayo',
    'ml' => 'Malayalam',
    'mt' => 'Maltés',
    'gv' => 'Manés',
    'mi' => 'Maorí',
    'mr' => 'Maratí',
    'mh' => 'Marshalés',
    'ro' => 'Rumano',
    'mn' => 'Mongol',
    'na' => 'Nauruano',
    'nv' => 'Navajo',
    'nd' => 'Ndebele del norte',
    'ng' => 'Ndonga',
    'ne' => 'Nepalí',
    'se' => 'Sami septentrional',
    'no' => 'Noruego',
    'nb' => 'Noruego Bokmål',
    'nn' => 'Noruego Nynorsk',
    'ii' => 'Yi de Sichuán',
    'oc' => 'Occitano',
    'oj' => 'Ojibwa',
    'or' => 'Oriya',
    'om' => 'Oromo',
    'os' => 'Osético ',
    'pi' => 'Pali',
    'pa' => 'Panyabí ',
    'ps' => 'Pastú',
    'fa' => 'Persa',
    'pl' => 'Polaco',
    'pt' => 'Portugués',
    'qu' => 'Quechua',
    'rm' => 'Romanche',
    'rn' => 'Kirundi',
    'ru' => 'Ruso',
    'sm' => 'Samoano',
    'sg' => 'Sango',
    'sa' => 'Sánscrito',
    'sc' => 'Sardo',
    'sr' => 'Serbio',
    'sn' => 'Shona',
    'sd' => 'Sindhi',
    'si' => 'Cingalés',
    'sk' => 'Eslovaco',
    'sl' => 'Esloveno',
    'so' => 'Somalí',
    'st' => 'Sesotho',
    'nr' => 'Ndebele del sur',
    'es' => 'Español',
    'su' => 'Sundanés',
    'sw' => 'Suajili',
    'ss' => 'Suazi',
    'sv' => 'Sueco',
    'tl' => 'Tagalo',
    'ty' => 'Tahitiano',
    'tg' => 'Tayiko',
    'ta' => 'Tamil',
    'tt' => 'Tártaro',
    'te' => 'Télugu',
    'th' => 'Tailandés',
    'bo' => 'Tibetano',
    'ti' => 'Tigriña',
    'to' => 'Tongano',
    'ts' => 'Tsonga',
    'tn' => 'Setsuana',
    'tr' => 'Turco',
    'tk' => 'Turcomano',
    'tw' => 'Twi',
    'ug' => 'Uigur',
    'uk' => 'Ucraniano',
    'ur' => 'Urdu',
    'uz' => 'Uzbeko',
    've' => 'Venda',
    'vi' => 'Vietnamíta',
    'vo' => 'Volapük',
    'wa' => 'Valón',
    'cy' => 'Galés',
    'fy' => 'Frisón',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yi' => 'Yídish',
    'yo' => 'Yoruba',
    'za' => 'Chuan',
    'zu' => 'Zulú'
    ];

    public function audio()
    {
        return $this->hasMany('App\Audio');
    }

    public function videos()
    {
        return $this->hasMany('App\Video');
    }

    public function texts()
    {
        return $this->hasMany('App\Text');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function last_update_user()
    {
        return $this->belongsTo('App\User','last_update_user_id');
    }
}
